<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13465" started-at="2021-07-27T20:46:16Z" finished-at="2021-07-27T20:46:30Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13465" started-at="2021-07-27T20:46:16Z" finished-at="2021-07-27T20:46:30Z">
      <class name="TestNGConcepts.LoginPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:TestNGConcepts.LoginPageTest@59f99ea]" name="setUp" is-config="true" duration-ms="7673" started-at="2021-07-28T02:16:16Z" finished-at="2021-07-28T02:16:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginTest()[pri:3, instance:TestNGConcepts.LoginPageTest@59f99ea]" name="loginTest" duration-ms="4812" started-at="2021-07-28T02:16:24Z" finished-at="2021-07-28T02:16:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Test case failed, Header text not matched expected [Nikhil 1 Pareek] but found [Nikhil Pareek],
	expected [12345] but found [Zoho Accounts]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Test case failed, Header text not matched expected [Nikhil 1 Pareek] but found [Nikhil Pareek],
	expected [12345] but found [Zoho Accounts]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at TestNGConcepts.LoginPageTest.loginTest(LoginPageTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestNGConcepts.LoginPageTest@59f99ea]" name="tearDown" is-config="true" duration-ms="960" started-at="2021-07-28T02:16:29Z" finished-at="2021-07-28T02:16:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestNGConcepts.LoginPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
